from typing import List
from  fusion.normalization import max_norm  # Adjust the import path as necessary

def min_max_norm(values: List[float]) -> List[float]: ...

def max_norm(values: List[float]) -> List[float]: ...

def borda_norm(ranks:List[int],scroes: List[float],num_candidates:int) -> List[float]: ...

def rank_norm(values: List[float]) -> List[float]: ...

def sum_norm(values: List[float]) -> List[float]: ...

def zmuv_norm(values: List[float]) -> List[float]: ...


